# Generated by Django 3.1.2 on 2020-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasseEstudantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nasc', models.CharField(max_length=8)),
                ('fone', models.CharField(max_length=11)),
                ('inst_ensino', models.CharField(max_length=40)),
                ('numero_cadastro', models.CharField(max_length=7)),
            ],
        ),
    ]
