# Generated by Django 3.1.2 on 2020-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeestudantil',
            name='data_nasc',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='passeestudantil',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
