# Generated by Django 3.1.2 on 2020-10-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201013_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nasc', models.DateField(max_length=8, verbose_name='Nascimento')),
                ('fone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('inst_ensino', models.CharField(max_length=40, verbose_name='Instituição de Ensino')),
                ('numero_cadastro', models.CharField(max_length=7, verbose_name='Nº do cadastro')),
            ],
        ),
        migrations.DeleteModel(
            name='PasseEstudantil',
        ),
    ]
