# Generated by Django 3.1.2 on 2020-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201013_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cadastro', models.CharField(max_length=9, verbose_name='Cadastro Nº')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('conf_senha', models.CharField(max_length=20, verbose_name='Confirmar Senha')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_nasc',
            field=models.DateField(max_length=8, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero_cadastro',
            field=models.CharField(max_length=9, verbose_name='Cadastro Nº'),
        ),
    ]
