# Generated by Django 3.1.2 on 2020-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201015_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Saldo atual')),
                ('valor_recarga', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da recarga')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Senha',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero_cadastro',
            field=models.CharField(max_length=7, verbose_name='Cadastro Nº'),
        ),
    ]
