# Generated by Django 3.1.2 on 2020-10-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201016_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cadastro'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
