# Generated by Django 3.1.2 on 2020-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201016_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alters_data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='recarga',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
