# Generated by Django 3.1.2 on 2020-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201020_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='data_recarga',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='utilizacao',
            name='data_recarga',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='utilizacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='DEFAULT VALUE', max_digits=6, verbose_name='Valor'),
        ),
    ]
