# Generated by Django 3.1.2 on 2020-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201021_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor'),
        ),
    ]
